default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: minhvuong
  password: qwertyuiop
  host: localhost
  port: 5432

development:
  <<: *default
  database: BongDaSo_development

test:
  <<: *default
  database: BongDaSo_test

production:
  <<: *default
  database: BongDaSo_production
